version: '3.8'

services:
  backend:
    build: ./server
    container_name: edupulse_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    volumes:
      - ./server/db.sqlite3:/app/db.sqlite3 # Persist your data

  frontend:
    build: ./edupulse
    container_name: edupulse_frontend
    ports:
      - "80:80" # Access via http://localhost
    depends_on:
      - backend